version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    command: uvicorn main:app --port 8000 --reload
    ports:
      - "8000:8000"
    networks:
      - tkffuwnj
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - tkffuwnj

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: h311on31ghb0r
      MYSQL_DATABASE: develop
      MYSQL_USER: dev
      MYSQL_PASSWORD: h311on31ghb0r
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tkffuwnj

networks:
  tkffuwnj:
    name: tkffuwnj

volumes:
  mysql_data:
