version: "3"
services:
  unicorn:
    build:
      context: .
      dockerfile: dockerfile
    image: unicorn:latest
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - tkffuwnj

networks:
  tkffuwnj:
    name: tkffuwnj
